# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        laUnes:
            quality: 75
            filters:
                upscale:
                    min: [738, 662]
                thumbnail:
                    size: [738, 662]
                    mode: outbound
        launesthumbail:
            quality: 50
            filters:
                thumbnail:
                    size: [65, 65]
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [500, 500]
                    mode:          outbound
                    allow_upscale: true
